// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef stygmaboutui_h
#define stygmaboutui_h
#include <FL/Fl.H>
#include <FL/Fl_Text_Buffer.H>
#include "stygmorgan.h"
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Tabs.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Text_Display.H>
#include <FL/Fl_Button.H>

class about {
public:
  about();
  Fl_Double_Window* make_window();
  Fl_Double_Window *aboutwin;
private:
  inline void cb_aboutwin_i(Fl_Double_Window*, void*);
  static void cb_aboutwin(Fl_Double_Window*, void*);
public:
  Fl_Group *Tab1;
  Fl_Box *progname;
  Fl_Group *Tab2;
  Fl_Text_Display *TDA;
  Fl_Text_Display *TDTh;
  Fl_Text_Display *TDT;
  Fl_Text_Display *TDL;
  Fl_Text_Display *TDD;
private:
  inline void cb_Close_i(Fl_Button*, void*);
  static void cb_Close(Fl_Button*, void*);
};
#endif
