// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef stygmhelpui_h
#define stygmhelpui_h
#include <FL/Fl.H>
#include "stygmorgan.h"
#include <FL/Fl_Help_Dialog.H>

class stygmhelp {
public:
  stygmhelp();
};
#endif
